# Theme metadata
name = "my_theme"

[light]
  # Primary
  primary = "#8C1515" ## ## Cardinal red

  # Menu
  menu_primary = "#fff"
  menu_text = "#8C1515" # "#34495e"
  menu_text_active = "#8C1515" # "#2962ff" # blue
  menu_title = "#2b2b2b" ## dark gray

  # Home sections
  home_section_odd = "rgb(255, 255, 255)" ## blue #"rgb(140, 21, 21)" ## Cardinal red #
  home_section_even = "rgb(247, 247, 247)" ## gray

[dark]
  # Primary
  primary = "#bbdefb"

  link = "#bbdefb"
  link_hover = "#bbdefb"
